'use client'

import Link from 'next/link'
import { ArrowLeft, Shield, Bot, Eye, MessageCircle, AlertTriangle, Heart } from 'lucide-react'

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-teal-50 via-yellow-50 to-orange-50 p-4 md:p-8">
      <div className="max-w-4xl mx-auto">
        {/* Navigation */}
        <div className="mb-8">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-teal-600 hover:text-teal-800 font-semibold"
          >
            <ArrowLeft className="w-5 h-5" />
            Back to Home
          </Link>
        </div>

        {/* Header */}
        <div className="bg-white rounded-3xl shadow-xl p-8 md:p-12 mb-8 border-2 border-teal-200">
          <div className="text-center mb-10">
            <div className="text-6xl mb-4">🦫</div>
            <h1 className="text-4xl md:text-5xl font-bold text-teal-700 mb-4">
              Terms & Conditions
            </h1>
            <p className="text-lg text-teal-600">
              Transparency, safety, and trust — here's how Little Story Bear works.
            </p>
            <p className="text-sm text-gray-500 mt-2">
              Last updated: February 2026
            </p>
          </div>

          {/* AI Disclosure */}
          <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl p-6 md:p-8 mb-8 border-2 border-blue-200">
            <div className="flex items-center gap-3 mb-4">
              <Bot className="w-8 h-8 text-blue-600" />
              <h2 className="text-2xl font-bold text-blue-700">AI-Generated Content Disclosure</h2>
            </div>
            <div className="space-y-4 text-gray-700">
              <p className="text-lg leading-relaxed">
                <strong>Little Story Bear uses artificial intelligence (AI) to create stories and illustrations.</strong> This
                means that all story text and images are generated by AI models, not written or drawn by humans.
              </p>
              <p className="leading-relaxed">
                Because AI generates this content, please be aware of the following:
              </p>
              <ul className="space-y-3 ml-4">
                <li className="flex items-start gap-3">
                  <AlertTriangle className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" />
                  <span>
                    <strong>Images may not be perfectly accurate.</strong> AI-generated illustrations are creative
                    interpretations, not photographs. Characters may look slightly different from page to page,
                    and scenes may not match real-world locations or objects exactly.
                  </span>
                </li>
                <li className="flex items-start gap-3">
                  <AlertTriangle className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" />
                  <span>
                    <strong>AI can produce unexpected results (hallucinations).</strong> AI models sometimes generate
                    content that is inaccurate, inconsistent, or doesn't match what was requested. A story about
                    an elephant might occasionally show a different animal, or a scene description might not
                    perfectly align with the illustration.
                  </span>
                </li>
                <li className="flex items-start gap-3">
                  <AlertTriangle className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" />
                  <span>
                    <strong>Stories are fictional.</strong> All content generated by our platform is entirely fictional
                    and should not be taken as factual information, educational material, or real-world guidance.
                  </span>
                </li>
              </ul>
            </div>
          </div>

          {/* Child Safety */}
          <div className="bg-gradient-to-r from-green-50 to-teal-50 rounded-2xl p-6 md:p-8 mb-8 border-2 border-green-200">
            <div className="flex items-center gap-3 mb-4">
              <Shield className="w-8 h-8 text-green-600" />
              <h2 className="text-2xl font-bold text-green-700">Child Safety & Content Guardrails</h2>
            </div>
            <div className="space-y-4 text-gray-700">
              <p className="text-lg leading-relaxed">
                <strong>We take children's safety extremely seriously.</strong> Our platform is designed from the
                ground up for young audiences, and we have built multiple layers of protection to ensure a safe,
                positive experience.
              </p>
              <h3 className="text-lg font-bold text-green-700 mt-6">Safety measures we have in place:</h3>
              <ul className="space-y-3 ml-4">
                <li className="flex items-start gap-2">
                  <span className="text-green-500 font-bold mt-0.5">&#10003;</span>
                  <span>
                    <strong>Input filtering:</strong> Story prompts are screened for inappropriate content before
                    any generation begins. Content that isn't suitable for children is blocked immediately.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-500 font-bold mt-0.5">&#10003;</span>
                  <span>
                    <strong>Kid-friendly style enforcement:</strong> All images are generated in a children's
                    picture book illustration style with bold outlines, vibrant colors, and friendly characters.
                    We actively block realistic, scary, or violent visual styles.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-500 font-bold mt-0.5">&#10003;</span>
                  <span>
                    <strong>Description sanitization:</strong> Even if a child describes something like a
                    "scary monster with sharp teeth," our safety filter automatically softens it into
                    age-appropriate alternatives like a "silly creature with a big smile."
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-500 font-bold mt-0.5">&#10003;</span>
                  <span>
                    <strong>Character library:</strong> Our pre-built library of kid-friendly animal characters
                    ensures consistent, safe, and appealing illustrations across stories.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-green-500 font-bold mt-0.5">&#10003;</span>
                  <span>
                    <strong>Negative prompt protection:</strong> Our image generation system uses extensive
                    negative prompts to prevent the creation of scary, violent, realistic, or otherwise
                    inappropriate imagery.
                  </span>
                </li>
              </ul>
              <p className="leading-relaxed mt-4 text-sm text-green-700 bg-green-100 rounded-lg p-4">
                While we work hard to maintain a safe environment, no automated system is perfect. We
                encourage parents and guardians to be involved in their child's storytelling experience
                and to report any content that seems inappropriate.
              </p>
            </div>
          </div>

          {/* How We Use AI */}
          <div className="bg-gradient-to-r from-purple-50 to-pink-50 rounded-2xl p-6 md:p-8 mb-8 border-2 border-purple-200">
            <div className="flex items-center gap-3 mb-4">
              <Eye className="w-8 h-8 text-purple-600" />
              <h2 className="text-2xl font-bold text-purple-700">How We Use AI Technology</h2>
            </div>
            <div className="space-y-4 text-gray-700">
              <p className="leading-relaxed">
                Our platform uses the following AI technologies to create stories:
              </p>
              <ul className="space-y-3 ml-4">
                <li className="flex items-start gap-2">
                  <span className="text-purple-500 font-bold mt-0.5">&#8226;</span>
                  <span>
                    <strong>Speech-to-text AI</strong> converts your child's spoken story ideas into text.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-purple-500 font-bold mt-0.5">&#8226;</span>
                  <span>
                    <strong>Large language models (LLMs)</strong> transform story ideas into full illustrated
                    storybook narratives with character development and page-by-page scenes.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-purple-500 font-bold mt-0.5">&#8226;</span>
                  <span>
                    <strong>Image generation models</strong> create the illustrations for each page of the
                    story. These are AI-generated images, not photographs or hand-drawn art.
                  </span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-purple-500 font-bold mt-0.5">&#8226;</span>
                  <span>
                    <strong>Text-to-speech AI</strong> can read stories aloud to children.
                  </span>
                </li>
              </ul>
              <p className="leading-relaxed mt-4">
                We do not use AI to collect, analyze, or profile children's personal information. The AI is
                used solely for creative content generation.
              </p>
            </div>
          </div>

          {/* Feedback & Improvement */}
          <div className="bg-gradient-to-r from-orange-50 to-yellow-50 rounded-2xl p-6 md:p-8 mb-8 border-2 border-orange-200">
            <div className="flex items-center gap-3 mb-4">
              <MessageCircle className="w-8 h-8 text-orange-600" />
              <h2 className="text-2xl font-bold text-orange-700">Your Feedback Matters</h2>
            </div>
            <div className="space-y-4 text-gray-700">
              <p className="text-lg leading-relaxed">
                <strong>We are actively improving our platform based on your feedback.</strong> This is an
                evolving product, and we are committed to making it better every day.
              </p>
              <p className="leading-relaxed">
                We want to hear from you about:
              </p>
              <ul className="space-y-2 ml-4">
                <li className="flex items-start gap-2">
                  <span className="text-orange-500 font-bold mt-0.5">&#10003;</span>
                  <span>Story quality and character consistency improvements</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-orange-500 font-bold mt-0.5">&#10003;</span>
                  <span>Any content that doesn't meet our safety standards</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-orange-500 font-bold mt-0.5">&#10003;</span>
                  <span>New features or animal characters you'd like to see</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-orange-500 font-bold mt-0.5">&#10003;</span>
                  <span>Your child's experience and what brought them joy</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-orange-500 font-bold mt-0.5">&#10003;</span>
                  <span>Bugs, unexpected behavior, or AI-generated content that seemed off</span>
                </li>
              </ul>
              <p className="leading-relaxed mt-4">
                Every piece of feedback helps us build a safer, more magical experience for kids.
                We read every message and use your input to prioritize improvements.
              </p>
              <div className="bg-orange-100 rounded-lg p-4 mt-4 text-center">
                <p className="font-semibold text-orange-700">
                  Have feedback or concerns? Reach out to us anytime.
                </p>
                <p className="text-sm text-orange-600 mt-1">
                  We're building this for your family, and your voice shapes what comes next.
                </p>
              </div>
            </div>
          </div>

          {/* Terms of Use */}
          <div className="bg-gray-50 rounded-2xl p-6 md:p-8 mb-8 border-2 border-gray-200">
            <h2 className="text-2xl font-bold text-gray-700 mb-4">Terms of Use</h2>
            <div className="space-y-4 text-gray-600 text-sm leading-relaxed">
              <p>
                By using Little Story Bear, you agree to the following terms:
              </p>
              <ol className="list-decimal ml-6 space-y-3">
                <li>
                  <strong>Age requirement:</strong> This platform is designed for children. If you are under
                  13, a parent or guardian must supervise your use of this service.
                </li>
                <li>
                  <strong>AI-generated content:</strong> You acknowledge that all stories and illustrations
                  are generated by artificial intelligence and may contain inaccuracies, inconsistencies, or
                  unexpected content. We are not responsible for AI hallucinations or generation errors.
                </li>
                <li>
                  <strong>Content ownership:</strong> Stories you create are yours to keep, share, and enjoy.
                  We do not claim ownership of the stories generated through our platform.
                </li>
                <li>
                  <strong>Acceptable use:</strong> You agree not to attempt to use our platform to generate
                  inappropriate, harmful, or offensive content. Our safety filters will block such attempts,
                  and repeated violations may result in account suspension.
                </li>
                <li>
                  <strong>No guarantees:</strong> While we strive for high-quality, consistent character
                  illustrations, AI generation is inherently variable. We cannot guarantee that characters
                  will look identical across every page or every story.
                </li>
                <li>
                  <strong>Service availability:</strong> We aim to keep our service running smoothly, but
                  cannot guarantee uninterrupted access. AI generation depends on third-party services that
                  may occasionally be unavailable.
                </li>
                <li>
                  <strong>Privacy:</strong> We respect your family's privacy. Voice recordings are processed
                  for transcription only and are not stored permanently. We do not sell personal data.
                </li>
                <li>
                  <strong>Changes to terms:</strong> We may update these terms as our platform evolves. We
                  will notify users of significant changes.
                </li>
              </ol>
            </div>
          </div>

          {/* Benny's Promise */}
          <div className="bg-teal-100 rounded-2xl p-6 md:p-8 border-2 border-teal-300 text-center">
            <Heart className="w-12 h-12 text-red-400 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-teal-700 mb-4">Our Promise to Families</h2>
            <p className="text-lg text-teal-800 leading-relaxed max-w-2xl mx-auto">
              We are parents and educators who built this platform because we believe in the
              power of storytelling. Your child's safety and joy are at the heart of everything
              we do. We will continue to improve our safety measures, our AI quality, and our
              platform based on your trust and feedback.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 text-center text-teal-600 text-sm">
          <p>Made with love for young storytellers everywhere</p>
          <div className="flex justify-center gap-4 mt-4">
            <Link href="/about" className="hover:text-teal-800 underline">About Us</Link>
            <Link href="/pricing" className="hover:text-teal-800 underline">Pricing</Link>
            <Link href="/" className="hover:text-teal-800 underline">Create a Story</Link>
          </div>
        </div>
      </div>
    </main>
  )
}
