import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

export async function POST(request: NextRequest) {
  try {
    const { prompt } = await request.json()

    if (!prompt || typeof prompt !== 'string') {
      return NextResponse.json(
        { error: 'Invalid prompt provided' },
        { status: 400 }
      )
    }

    console.log('📖 Generating unique 4-page story with OpenAI from:', prompt)

    // Use OpenAI GPT-4 to generate a unique, kid-friendly 4-page story (like Gemini Storybook)
    const completion = await openai.chat.completions.create({
      model: 'gpt-4',
      messages: [
        {
          role: 'system',
          content: `You are a creative children's story writer. Create engaging, unique 4-page stories for kids aged 4-8 based on their ideas (like Google Gemini Storybook format).

IMPORTANT RULES:
- Create a UNIQUE story based on what the child says - don't use generic templates
- The story should be EXACTLY 4 pages long
- Each page should be 4-6 sentences - rich, engaging content
- Include a clear beginning, middle, and end
- Include a simple problem and how it's solved
- Keep it kid-friendly, non-religious, non-political
- Make it fun, magical, and age-appropriate
- Use the EXACT character names and details the child mentions
- Each page should describe a vivid, colorful visual scene

FORMAT YOUR RESPONSE EXACTLY LIKE THIS:
TITLE: [Creative title based on their idea]

PAGE 1:
[4-6 sentences - introduction of main character and their world, set the scene beautifully]

PAGE 2:
[4-6 sentences - adventure begins, problem is discovered, character reacts]

PAGE 3:
[4-6 sentences - working to solve the problem, teamwork, trying different solutions]

PAGE 4:
[4-6 sentences - problem solved, celebration, what they learned, happy ending]`
        },
        {
          role: 'user',
          content: `A child wants a story about: "${prompt}". Create a unique, magical 4-page story based on their idea!`
        }
      ],
      temperature: 0.9,
      max_tokens: 1200,
    })

    const storyText = completion.choices[0].message.content || ''
    console.log('✅ 4-page story generated by OpenAI GPT-4')

    // Parse the story
    const story = parseStory(storyText, prompt)

    // Generate image prompts for each page
    const imagePrompts = generateImagePrompts(story, prompt)

    return NextResponse.json({
      story: {
        title: story.title,
        pages: story.pages,
      },
      imagePrompts,
    })
  } catch (error) {
    console.error('Error generating story:', error)
    return NextResponse.json(
      { error: 'Failed to generate story. Please try again.' },
      { status: 500 }
    )
  }
}

function generateImagePrompts(story: any, originalPrompt: string): string[] {
  // Vibrant, colorful art style like Gemini Storybook - very specific and detailed
  const artStyle = "Vibrant colorful children's book illustration, Disney Pixar animation style, highly saturated rich colors, dramatic lighting with glowing effects, magical sparkles and stars, whimsical fantasy atmosphere, professional digital painting, ultra detailed, cinematic quality"

  // Extract character details from the original prompt
  const lowerPrompt = originalPrompt.toLowerCase()

  // Extract specific character description
  let characterDescription = ''

  // Try to extract full character description - checking for common animals
  if (lowerPrompt.includes('lion')) {
    const lionMatch = originalPrompt.match(/lion[^.!?,]*/i)
    characterDescription = lionMatch ? lionMatch[0] : 'lion'
  } else if (lowerPrompt.includes('dog')) {
    const dogMatch = originalPrompt.match(/dog[^.!?,]*/i)
    characterDescription = dogMatch ? dogMatch[0] : 'dog'
  } else if (lowerPrompt.includes('cat')) {
    const catMatch = originalPrompt.match(/cat[^.!?,]*/i)
    characterDescription = catMatch ? catMatch[0] : 'cat'
  } else if (lowerPrompt.includes('dragon')) {
    const dragonMatch = originalPrompt.match(/dragon[^.!?,]*/i)
    characterDescription = dragonMatch ? dragonMatch[0] : 'dragon'
  } else if (lowerPrompt.includes('unicorn')) {
    characterDescription = 'unicorn'
  } else {
    // Try to extract any character description
    const characterMatch = originalPrompt.match(/(?:a|an|the)\s+([^.!?,]+?)(?:\s+who|\s+that|goes|went|$)/i)
    characterDescription = characterMatch ? characterMatch[1] : 'friendly character'
  }

  console.log('🎨 Character description extracted:', characterDescription)

  // Generate detailed prompts for 4 pages - ultra vibrant like Gemini
  const prompts = [
    // Page 1: Introduction - vibrant, colorful establishing shot
    `${artStyle}. A cute adorable ${characterDescription} with huge expressive eyes and friendly smile, in a magical vibrant world with glowing colors, rainbow skies, sparkling nature, bright cheerful atmosphere. Ultra colorful and detailed. The character is the main focus with dramatic lighting highlighting them.`,

    // Page 2: Adventure/Problem - dynamic, exciting scene
    `${artStyle}. ${characterDescription} on an exciting adventure, dynamic action pose, discovering something mysterious with glowing magical effects, vibrant dramatic landscape with rich saturated colors, mystical glowing lights and sparkles everywhere. Very colorful and energetic scene.`,

    // Page 3: Solving/Teamwork - warm, cooperative scene with multiple characters
    `${artStyle}. ${characterDescription} working together with colorful friendly animal characters (rabbits, birds, squirrels), all with big expressive eyes, cooperating as a team with magical glowing energy connecting them, vibrant forest clearing with rainbow light beams, ultra saturated warm colors. Heartwarming teamwork scene.`,

    // Page 4: Happy ending - celebration with maximum vibrancy
    `${artStyle}. ${characterDescription} celebrating joyfully with all their colorful animal friends, everyone dancing and cheering, magical sparkles and fireworks in a vibrant sunset sky with purple pink orange gold colors, glowing magical effects everywhere, ultra bright and cheerful. Perfect happy ending with maximum color and joy.`
  ]

  return prompts
}

function parseStory(text: string, originalPrompt: string) {
  // Extract title
  const titleMatch = text.match(/TITLE:\s*(.+?)(?:\n|PAGE)/i)
  const title = titleMatch ? titleMatch[1].trim() : 'My Amazing Story'

  // Extract pages (looking for 4 pages)
  const pages: { text: string }[] = []

  for (let i = 1; i <= 4; i++) {
    const pageRegex = new RegExp(`PAGE ${i}:\\s*(.+?)(?=PAGE ${i + 1}:|$)`, 'is')
    const pageMatch = text.match(pageRegex)

    if (pageMatch) {
      const pageText = pageMatch[1].trim()
      // Clean up any extra whitespace
      const cleanedText = pageText.replace(/\n\n+/g, ' ').trim()
      pages.push({ text: cleanedText })
    }
  }

  // Fallback if parsing fails - split into 4 pages
  if (pages.length < 3) {
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 20)
    const sentencesPerPage = Math.max(4, Math.floor(sentences.length / 4))

    pages.length = 0 // Clear any partial pages
    for (let i = 0; i < 4; i++) {
      const start = i * sentencesPerPage
      const end = start + sentencesPerPage
      const pageText = sentences.slice(start, end).join('. ') + '.'
      if (pageText.trim().length > 10) {
        pages.push({ text: pageText.trim() })
      }
    }
  }

  // Final fallback - create 4 rich pages
  if (pages.length < 3) {
    const char = extractCharacterName(originalPrompt)
    pages.length = 0
    pages.push(
      { text: `Once upon a time in a magical land, there lived a wonderful ${char} with the brightest eyes and kindest heart. Every day was filled with wonder and excitement as ${char} explored the beautiful world around them. The sun always seemed to shine a little brighter whenever ${char} was near, and all the animals in the forest were their friends.` },
      { text: `One special day, ${char} discovered that something magical was happening! A mysterious challenge appeared that needed to be solved. ${char} knew this was important and decided to be brave. With determination in their heart, ${char} set off on an incredible adventure to make things right.` },
      { text: `${char} met wonderful friends along the way who wanted to help. Together, they worked as a team, each contributing their special talents. With cooperation, creativity, and courage, they faced every obstacle. The power of friendship and teamwork made them unstoppable!` },
      { text: `With one final burst of effort, ${char} and their friends solved the problem! Everyone celebrated with joy and laughter under a beautiful rainbow sky. ${char} learned that with good friends and a brave heart, anything is possible. And they all lived happily ever after, ready for the next great adventure!` }
    )
  }

  // Ensure exactly 4 pages
  while (pages.length < 4) {
    pages.push({ text: 'And the magical adventure continued with wonder and joy...' })
  }

  return {
    title,
    pages: pages.slice(0, 4),
  }
}

function extractCharacterName(prompt: string): string {
  const lowerPrompt = prompt.toLowerCase()

  // Try to find a character type
  const animals = ['dog', 'cat', 'dragon', 'unicorn', 'bear', 'lion', 'elephant', 'monkey', 'rabbit', 'fox', 'dinosaur', 'bird']
  for (const animal of animals) {
    if (lowerPrompt.includes(animal)) {
      return animal
    }
  }

  const people = ['princess', 'prince', 'knight', 'wizard', 'fairy', 'pirate']
  for (const person of people) {
    if (lowerPrompt.includes(person)) {
      return person
    }
  }

  return 'our hero'
}
