import { NextRequest, NextResponse } from 'next/server'
import Replicate from 'replicate'

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
})

export async function POST(request: NextRequest) {
  try {
    const { prompt } = await request.json()

    if (!prompt || typeof prompt !== 'string') {
      return NextResponse.json(
        { error: 'Invalid prompt provided' },
        { status: 400 }
      )
    }

    console.log('📖 Generating unique 10-page story with Replicate Llama from:', prompt)

    // Use Replicate Llama 3.3 70B (FREE!) to generate story
    const systemPrompt = `You are a creative children's story writer. Create engaging, unique 10-page stories for kids aged 4-8 based on their ideas (like Google Gemini Storybook format).

IMPORTANT RULES:
- Create a UNIQUE story based on what the child says - don't use generic templates
- The story should be EXACTLY 10 pages long
- Each page should be 5-8 sentences - rich, engaging, detailed content
- Include a clear beginning, middle, and end with good pacing
- Include a simple problem and how it's solved
- Keep it kid-friendly, non-religious, non-political
- Make it fun, magical, and age-appropriate
- Use the EXACT character names and details the child mentions
- Each page should describe a vivid visual scene with soft pastel colors

FORMAT YOUR RESPONSE EXACTLY LIKE THIS:
TITLE: [Creative title based on their idea]

PAGE 1:
[5-8 sentences - introduction of main character, their personality, and their beautiful world]

PAGE 2:
[5-8 sentences - character's daily life, what they love to do, their friends]

PAGE 3:
[5-8 sentences - something interesting happens, adventure begins]

PAGE 4:
[5-8 sentences - problem or challenge is discovered, character reacts with emotion]

PAGE 5:
[5-8 sentences - character decides to face the challenge, gathers courage]

PAGE 6:
[5-8 sentences - working to solve problem, trying first approach]

PAGE 7:
[5-8 sentences - setback or complication, character learns something important]

PAGE 8:
[5-8 sentences - teamwork and new strategy, friends help]

PAGE 9:
[5-8 sentences - problem solved successfully, moment of triumph]

PAGE 10:
[5-8 sentences - celebration, what they learned, happy ending with friends and family]`

    const userPrompt = `A child wants a story about: "${prompt}". Create a unique, magical 10-page story based on their idea!`

    const output = await replicate.run(
      "meta/meta-llama-3.1-405b-instruct",
      {
        input: {
          prompt: `${systemPrompt}\n\n${userPrompt}`,
          temperature: 0.9,
          max_tokens: 3000,
          top_p: 0.9,
        }
      }
    ) as string[]

    const storyText = output.join('')
    console.log('✅ 10-page story generated by Replicate Llama (FREE!)')

    // Parse the story
    const story = parseStory(storyText, prompt)

    // Generate image prompts for each page
    const imagePrompts = generateImagePrompts(story, prompt)

    return NextResponse.json({
      story: {
        title: story.title,
        pages: story.pages,
      },
      imagePrompts,
    })
  } catch (error) {
    console.error('Error generating story:', error)
    return NextResponse.json(
      { error: 'Failed to generate story. Please try again.' },
      { status: 500 }
    )
  }
}

function generateImagePrompts(story: any, originalPrompt: string): string[] {
  // Soft pastel art style - gentle and calming
  // Use positive framing (what we WANT) instead of negative (NO TEXT) - FLUX follows this better
  const baseStyle = "Wordless illustration, textless children's book art, silent picture book style, soft pastel watercolor, gentle visual storytelling, muted pastel colors (baby pink, lavender, mint green, peach, cream, powder blue), soft diffused lighting, dreamy ethereal atmosphere, delicate gentle tones, cozy and warm"

  console.log('🎨 Generating image prompts from actual story pages...')

  // Generate a specific image prompt for each page based on its content
  const prompts = story.pages.map((page: any, index: number) => {
    const pageText = page.text

    // Extract first two sentences for main visual content (usually has key details)
    const sentences = pageText.split(/[.!?]+/).filter((s: string) => s.trim().length > 10)
    const keyContent = sentences.slice(0, 2).join('. ')

    // Create scene-specific prompt based on story arc
    let prompt = `${baseStyle}. `

    // Different scenes for 10-page book
    if (index === 0) {
      // Page 1: Character introduction
      prompt += `Opening scene: ${keyContent}. Show the main character with gentle expressive eyes in a soft, dreamy world. Peaceful, warm establishing shot with pastel sky.`
    } else if (index === 1) {
      // Page 2: Daily life
      prompt += `Daily life scene: ${keyContent}. Show the character enjoying peaceful moments with friends. Soft, cozy atmosphere with gentle pastel tones.`
    } else if (index === 2) {
      // Page 3: Adventure begins
      prompt += `Adventure beginning: ${keyContent}. Show gentle curiosity and wonder. Soft magical elements with delicate sparkles in pastel colors.`
    } else if (index === 3) {
      // Page 4: Problem discovered
      prompt += `Discovery scene: ${keyContent}. Show the character with gentle concern but hopeful expression. Soft dramatic mood with muted pastel palette.`
    } else if (index === 4) {
      // Page 5: Gathering courage
      prompt += `Courage scene: ${keyContent}. Show determination with soft brave energy. Warm encouraging atmosphere in gentle tones.`
    } else if (index === 5) {
      // Page 6: First attempt
      prompt += `Action scene: ${keyContent}. Show the character trying their best. Soft dynamic movement with pastel colors and gentle lighting.`
    } else if (index === 6) {
      // Page 7: Learning moment
      prompt += `Learning scene: ${keyContent}. Show thoughtful reflection and wisdom. Calm, peaceful mood with soft warm light.`
    } else if (index === 7) {
      // Page 8: Teamwork
      prompt += `Teamwork scene: ${keyContent}. Show friends working together with gentle cooperation. Warm friendly atmosphere in soft pastel hues.`
    } else if (index === 8) {
      // Page 9: Success
      prompt += `Triumph scene: ${keyContent}. Show gentle joy and success. Soft celebration with delicate pastel rainbow colors and warm glow.`
    } else {
      // Page 10: Happy ending
      prompt += `Happy ending scene: ${keyContent}. Joyful celebration with all characters in a cozy, loving embrace. Soft magical happiness with gentle pastel colors and warm golden light.`
    }

    prompt += ` Wordless visual scene, textless illustration, silent storybook watercolor art, safe and comforting for kids 4-8 years old.`

    return prompt
  })

  console.log(`✅ Generated ${prompts.length} page-specific image prompts`)
  prompts.forEach((p, i) => {
    console.log(`Page ${i + 1} prompt: ${p.substring(0, 100)}...`)
  })

  return prompts
}

function parseStory(text: string, originalPrompt: string) {
  // Extract title
  const titleMatch = text.match(/TITLE:\s*(.+?)(?:\n|PAGE)/i)
  const title = titleMatch ? titleMatch[1].trim() : 'My Amazing Story'

  // Extract pages (looking for 10 pages)
  const pages: { text: string }[] = []

  for (let i = 1; i <= 10; i++) {
    const pageRegex = new RegExp(`PAGE ${i}:\\s*(.+?)(?=PAGE ${i + 1}:|$)`, 'is')
    const pageMatch = text.match(pageRegex)

    if (pageMatch) {
      const pageText = pageMatch[1].trim()
      // Clean up any extra whitespace
      const cleanedText = pageText.replace(/\n\n+/g, ' ').trim()
      pages.push({ text: cleanedText })
    }
  }

  // Fallback if parsing fails - split into 10 pages
  if (pages.length < 8) {
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 20)
    const sentencesPerPage = Math.max(5, Math.floor(sentences.length / 10))

    pages.length = 0 // Clear any partial pages
    for (let i = 0; i < 10; i++) {
      const start = i * sentencesPerPage
      const end = start + sentencesPerPage
      const pageText = sentences.slice(start, end).join('. ') + '.'
      if (pageText.trim().length > 10) {
        pages.push({ text: pageText.trim() })
      }
    }
  }

  // Final fallback - create 10 rich pages
  if (pages.length < 8) {
    const char = extractCharacterName(originalPrompt)
    pages.length = 0
    pages.push(
      { text: `Once upon a time in a soft, dreamy land painted in gentle pastel colors, there lived a wonderful ${char} with the brightest eyes and kindest heart. Their home was filled with warmth and love, surrounded by flowering meadows in shades of lavender and peach. Every day was filled with wonder and excitement as ${char} explored the beautiful world around them. The sun always seemed to shine with a soft golden glow whenever ${char} was near.` },
      { text: `Each morning, ${char} would wake up to the sweet songs of bluebirds and butterflies dancing outside the window. They loved to spend time with their best friends, playing gentle games and sharing stories. The days were peaceful and happy, filled with laughter and joy. ${char} felt grateful for all the beauty and friendship that surrounded them every single day.` },
      { text: `One special morning, something unusual caught ${char}'s attention - a gentle shimmer in the air, like tiny sparkles of soft light. The sparkles seemed to be calling out, inviting ${char} to follow them on an adventure. ${char} felt curious and excited, wondering where this magical trail might lead. With a deep breath and a hopeful smile, ${char} decided to follow the gentle lights.` },
      { text: `As ${char} followed the sparkles deeper into the enchanted forest, they discovered that something important was happening. A beautiful rainbow had lost its colors and had faded to pale gray. The forest creatures gathered around, looking worried and sad. ${char} felt their heart fill with determination - they knew they had to help bring back the rainbow's beautiful colors. This was going to be an important adventure.` },
      { text: `${char} stood tall and brave, even though the task seemed big and challenging. They remembered all the kind things their friends had taught them about courage and helping others. Taking a deep breath, ${char} decided to search for the magic that could restore the rainbow's colors. They packed a small bag with supplies and set off with hope in their heart, ready to do whatever it took to help.` },
      { text: `Along the winding path, ${char} tried to gather colors from flowers and butterflies, thinking they could paint the rainbow back to life. They collected petals of pink roses, yellow daisies, and blue forget-me-nots in a gentle basket. ${char} climbed up to where the rainbow touched the ground and carefully tried to sprinkle the colors onto it. The rainbow glowed softly for a moment, but the colors didn't quite stick. ${char} realized they needed to try something different.` },
      { text: `Sitting down to rest and think, ${char} felt a little discouraged but not defeated. A wise old owl landed nearby and spoke in a gentle voice: "True colors come from joy and love shared with friends." ${char} understood now - they needed to bring their friends together! This wasn't a challenge to face alone. ${char} felt excited and hopeful again, learning that asking for help is a sign of wisdom, not weakness.` },
      { text: `${char} hurried back and gathered all their dear friends - the rabbits, the deer, the squirrels, and the birds. Each friend brought their own special gift: songs of joy, dances of happiness, stories of love, and acts of kindness. Together, they formed a circle beneath the faded rainbow and shared all the beautiful, warm feelings in their hearts. The air began to shimmer and glow with gentle light as their friendship and love filled the space around them.` },
      { text: `Suddenly, like magic born from pure love and friendship, colors began to bloom across the rainbow! Soft pink, gentle yellow, peaceful blue, lovely green, and warm purple spread across the sky in the most beautiful arch anyone had ever seen. The colors were even more beautiful than before - softer, warmer, more magical. ${char} and all their friends cheered and danced with joy! They had done it together! The rainbow sparkled with happiness, grateful for the love that had brought it back to life.` },
      { text: `The whole forest celebrated with a wonderful party filled with music, dancing, and delicious treats. ${char} realized something very important: the most powerful magic in the world comes from friendship, kindness, and working together. The rainbow would forever remember the love that saved it, and ${char} would forever remember this magical adventure. As the sun set in beautiful pastel colors, ${char} hugged all their friends tightly, knowing that together, they could overcome anything. And they all lived happily ever after, ready for whatever adventures tomorrow might bring!` }
    )
  }

  // Ensure exactly 10 pages
  while (pages.length < 10) {
    pages.push({ text: 'And the magical adventure continued with wonder, love, and joy...' })
  }

  return {
    title,
    pages: pages.slice(0, 10),
  }
}

function extractCharacterName(prompt: string): string {
  const lowerPrompt = prompt.toLowerCase()

  // Try to find a character type
  const animals = ['dog', 'cat', 'dragon', 'unicorn', 'bear', 'lion', 'elephant', 'monkey', 'rabbit', 'fox', 'dinosaur', 'bird']
  for (const animal of animals) {
    if (lowerPrompt.includes(animal)) {
      return animal
    }
  }

  const people = ['princess', 'prince', 'knight', 'wizard', 'fairy', 'pirate']
  for (const person of people) {
    if (lowerPrompt.includes(person)) {
      return person
    }
  }

  return 'our hero'
}
